<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA & PEMROGRAMAN**

**“TIPE DATA, VARIABEL, INPUT, BOOLEAN, DAN KONSTANTA”**

**PEKAN 2**

**Disusun Oleh :**

**Azanel Adi Putro**

**2611532027**

**Kelas A**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Nama Asisten**

<br>

<img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur penulis panjatkan kehadirat Tuhan Yang Maha Esa karena atas rahmat dan karunia-Nya penulis dapat menyelesaikan laporan praktikum Algoritma dan Pemrograman pekan ke-2.

Praktikum ini membahas penggunaan variabel, tipe data string dan numerik, boolean, input, serta konstanta dalam Python. Selain itu, praktikum juga menerapkan konsep-konsep tersebut dalam sebuah program tugas yang mengolah data praktikan dan menentukan status kelulusan berdasarkan nilai.

Laporan ini disusun untuk mendokumentasikan seluruh latihan yang telah dilakukan serta menjelaskan alur logika program tugas secara rinci. Penulis menyadari bahwa laporan ini masih memiliki kekurangan sehingga kritik dan saran yang membangun sangat diharapkan.

Padang, 2026

Penulis

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang

Dalam pemrograman Python, variabel dan tipe data merupakan dasar yang digunakan untuk menyimpan serta mengolah informasi. Setiap data memiliki karakteristik berbeda, misalnya teks menggunakan tipe `string`, bilangan bulat menggunakan `int`, bilangan desimal menggunakan `float`, bilangan kompleks menggunakan `complex`, dan nilai logika menggunakan `bool`.

Selain tipe data, program sering membutuhkan masukan dari pengguna melalui `input()`, nilai tetap melalui konstanta, serta kondisi boolean untuk menghasilkan keputusan. Pemahaman terhadap konsep tersebut penting karena hampir seluruh program menggunakan data yang disimpan dalam variabel dan diproses berdasarkan tipe datanya.

## 1.2 Tujuan

1. Memahami konsep variabel dan tipe data pada Python.
2. Memahami penggunaan tipe data string, integer, float, complex, dan boolean.
3. Memahami cara menerima data menggunakan `input()`.
4. Memahami penggunaan konstanta dalam perhitungan.
5. Menganalisis alur logika program tugas yang mengolah data praktikan dan status kelulusan.

## 1.3 Manfaat

1. Menambah pemahaman dasar mengenai pengelolaan data dalam Python.
2. Melatih penggunaan variabel dengan tipe data yang sesuai.
3. Melatih proses konversi data input menjadi tipe numerik.
4. Memahami penerapan boolean untuk pengambilan keputusan.
5. Meningkatkan kemampuan membaca dan menganalisis alur program.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

1. **Variabel**  
   Variabel adalah nama yang digunakan untuk menyimpan suatu nilai. Dalam Python, tipe data variabel mengikuti nilai yang diberikan kepadanya.

2. **String**  
   `string` digunakan untuk menyimpan data berupa teks. String dapat ditulis menggunakan tanda kutip tunggal, tanda kutip ganda, atau triple quote untuk teks beberapa baris.

3. **Tipe data numerik**  
   Python menyediakan beberapa tipe numerik, antara lain `int` untuk bilangan bulat, `float` untuk bilangan desimal, dan `complex` untuk bilangan kompleks.

4. **Boolean**  
   Boolean hanya memiliki dua nilai, yaitu `True` dan `False`. Boolean dapat dihasilkan dari suatu perbandingan, misalnya `nilai >= batas`.

5. **Input**  
   Fungsi `input()` digunakan untuk menerima masukan dari pengguna. Nilai yang diterima dari `input()` pada dasarnya berupa string sehingga perlu dikonversi menggunakan `int()` atau `float()` jika akan digunakan sebagai angka.

6. **Konstanta**  
   Konstanta merupakan nilai yang dimaksudkan untuk tetap digunakan selama program. Pada latihan digunakan `Final` untuk menandai nilai `PI` sebagai konstanta.

## 2.2 Latihan Praktikum

### 2.2.1 Latihan String

**Program:** deklarasi dan menampilkan variabel bertipe string.

In [1]:
# data variables
nama_2027 = "azanel adi putro"
jenis_kelamin_2027 = 'L'
alamat_2027 = """
    Jl. Dr.muhammad Hatta No. 1
    kec. Padang Timur
    Kota Padang
"""
agama_2027 = "Islam"

# print the data variables
print("Nama saya adalah: ", nama_2027)
print("Jenis kelamin saya adalah: ", jenis_kelamin_2027)
print("Alamat saya adalah: ", alamat_2027)
print("Agama saya adalah: ", agama_2027)

Nama saya adalah:  azanel adi putro
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Jl. Dr.muhammad Hatta No. 1
    kec. Padang Timur
    Kota Padang

Agama saya adalah:  Islam


**Penjelasan:**

1. `nama_2027` menyimpan nama dalam bentuk string.
2. `jenis_kelamin_2027` menyimpan karakter `L` sebagai string.
3. `alamat_2027` menggunakan triple quote sehingga teks dapat ditulis dalam beberapa baris.
4. `agama_2027` menyimpan teks `"Islam"`.
5. Fungsi `print()` digunakan untuk menampilkan seluruh nilai variabel.

**Alur logika:** program membuat variabel → masing-masing variabel diberi nilai string → nilai variabel dicetak satu per satu. Tidak terdapat formula matematis pada latihan ini.

### 2.2.2 Latihan Numerik

**Program:** mengenali tipe data `int`, `float`, dan `complex`.

In [2]:
# create a variable with numeric type value
a_2027 = 100
print("The type of variable having value", a_2027, " is ", type(a_2027))

# create a variable with float value.
b_2027 = 10.2345
print("The type of variable having value", b_2027, " is ", type(b_2027))

# create a variable with complex value.
c_2027 = 100 + 3j
print("The type of variable having value", c_2027, " is ", type(c_2027))

The type of variable having value 100  is  <class 'int'>
The type of variable having value 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan:**

1. `a_2027 = 100` merupakan bilangan bulat sehingga bertipe `int`.
2. `b_2027 = 10.2345` memiliki nilai desimal sehingga bertipe `float`.
3. `c_2027 = 100 + 3j` merupakan bilangan kompleks sehingga bertipe `complex`.
4. Fungsi `type()` digunakan untuk mengetahui tipe data dari masing-masing variabel.

**Alur logika:** nilai numerik dibuat → Python menentukan tipe berdasarkan bentuk nilai → `type()` memeriksa tipe → hasil tipe ditampilkan.

### 2.2.3 Latihan Boolean

**Program:** menentukan status kelulusan menggunakan boolean dan operator logika.

In [3]:
# deklarasi variabel dengan tipe data boolean
is_lulus_2027 = True
is_cumlaude_2027= True

# menggunakan boolean
nilai_2027 = 85
batas_lulus_2027 = 75

# menentukan nilai boolean dari kondisi
status_kelulusan_2027 = nilai_2027 >= batas_lulus_2027 # Hasilnya akan True

# mencetak nilai boolean
print("=== Check Kelulusan ===")
print("Nilai:", nilai_2027)
print("Apakah lulus?:", status_kelulusan_2027)
if is_lulus_2027 and is_cumlaude_2027:
    print("Selamat, Anda lulus dengan peringkat cumlaude!")

=== Check Kelulusan ===
Nilai: 85
Apakah lulus?: True
Selamat, Anda lulus dengan peringkat cumlaude!


**Penjelasan:**

1. `is_lulus_2027` dan `is_cumlaude_2027` diberi nilai `True`.
2. `nilai_2027` berisi 85 dan `batas_lulus_2027` berisi 75.
3. Perbandingan `85 >= 75` menghasilkan `True`, kemudian disimpan pada `status_kelulusan_2027`.
4. Kondisi `if` menggunakan operator `and`. Karena kedua variabel boolean bernilai `True`, pesan kelulusan cumlaude ditampilkan.

**Formula/logika:** `status_kelulusan_2027 = nilai_2027 >= batas_lulus_2027`.

**Alur:** masukkan nilai dan batas → bandingkan nilai dengan batas → hasil menjadi `True/False` → cek dua kondisi dengan `and` → jika keduanya `True`, cetak pesan.

### 2.2.4 Latihan Input

**Program:** menghitung luas persegi panjang berdasarkan panjang dan lebar yang dimasukkan pengguna.

In [4]:
panjang_2027 = input("Masukkan nilai panjang: ")
lebar_2027 = input("Masukkan nilai lebar: ")
luas_2027 = int(panjang_2027) * int(lebar_2027)

print("Luas persegi panjang adalah: ", luas_2027)

ValueError: invalid literal for int() with base 10: ''

**Penjelasan:**

1. `input()` menerima panjang dan lebar dari pengguna.
2. Karena hasil `input()` berupa string, kedua nilai dikonversi menjadi integer menggunakan `int()`.
3. Luas dihitung menggunakan perkalian panjang dan lebar.
4. Hasil luas ditampilkan dengan `print()`.

**Formula matematis:**  
**L = p × l**

Dengan contoh `p = 10` dan `l = 5`, maka `L = 10 × 5 = 50`.

**Alur:** input panjang → input lebar → konversi ke integer → hitung luas → tampilkan hasil.

### 2.2.5 Latihan Konstanta

**Program:** menggunakan `PI` sebagai nilai tetap untuk menghitung luas lingkaran.

In [ ]:
from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_2027 = float(input("Masukkan nilai jari-jari: "))
luas_2027 = PI * jari_2027 * jari_2027
print("Luas lingkaran dengan jari-jari %.2f adalah: %.2f" % (jari_2027, luas_2027))

pi: 3.140000
Masukkan nilai jari-jari: 7
Luas lingkaran dengan jari-jari 7.00 adalah: 153.86

**Penjelasan:**

1. `Final` diimpor dari modul `typing`.
2. `PI` diberi nilai `3.14` dan ditandai sebagai `Final`.
3. Jari-jari diterima melalui `input()` dan dikonversi menjadi `float`.
4. Luas lingkaran dihitung menggunakan `PI * jari_2027 * jari_2027`.
5. Format `%.2f` digunakan untuk menampilkan dua angka di belakang koma.

**Formula matematis:**  
**L = π × r²**

Dengan `π = 3,14` dan `r = 7`, maka `L = 3,14 × 7² = 153,86`.

**Alur:** tetapkan `PI` → input jari-jari → konversi ke float → hitung `πr²` → tampilkan hasil.

---
## Tugas Praktikum

### 2.3 Program Tugas – Sistem Registrasi Praktikan Alpro

Program tugas menggabungkan beberapa konsep pekan 2, yaitu variabel global, string, integer, float, complex, boolean, input, fungsi, konversi tipe data, dan operasi perbandingan.

**Kode Program:**

In [5]:
# ===== VARIABEL GLOBAL =====
nama_2027 = "..."
kelamin_2027 = '-'
umur_2027 = 0
skor_2027 = 0.0
batas_minimum_2027 = 75.0
lulus_2027= False
token_2027 = 6767 + 3j
alamat_2027 = """
Perumahan indah permai,
Jl. Dr.muhammad hatta no 1,
Kec. Padang Timur
Kota padang """

def main():
    print("=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===")
    bagian1()
    print("\n=== DATA PRAKTIKAN & HASIL PEMERIKASAAN ===")
    bagian2()
    print("\n=== STATUS KELULUSAN PRAKTIKUM ===")
    bagian3()

def bagian1():
    global nama_2027
    global kelamin_2027
    global umur_2027
    global skor_2027
    nama_2027 = input("Masukkan Nama Mahasiswa     : ")
    kelamin_2027 = input("Masukkan Jenis Kelamin (L/P): ")
    umur_2027 = int(input("Masukkan Umur               : "))
    skor_2027 = float(input("Masukkan Skor Tes Awal      : "))

def bagian2():
    print("Nama Mahasiswa :", nama_2027, "| Tipe: ", type(nama_2027))
    print("Jenis Kelamin  :", kelamin_2027, "| Tipe: ", type(kelamin_2027))
    print("Alamat Domisili:", alamat_2027, "| Tipe: ", type(alamat_2027))
    print("Umur           :", umur_2027, "tahun | Tipe: ", type(umur_2027))
    print("Skor Tes Awal  :", skor_2027, "| Tipe: ", type(skor_2027))
    print("ID Token Sinyal:", token_2027, "| Tipe: ", type(token_2027))

def bagian3():
    global lulus_2027
    print("Batas Minimum Nilai:",batas_minimum_2027)
    lulus_2027 = skor_2027 >= batas_minimum_2027
    print("Apakah Dinyatakan Lulus?:", lulus_2027, "| Tipe: ", type(lulus_2027)) 

main()

=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===

=== DATA PRAKTIKAN & HASIL PEMERIKASAAN ===
Nama Mahasiswa : azanel | Tipe:  <class 'str'>
Jenis Kelamin  : L | Tipe:  <class 'str'>
Alamat Domisili: 
Perumahan indah permai,
Jl. Dr.muhammad hatta no 1,
Kec. Padang Timur
Kota padang  | Tipe:  <class 'str'>
Umur           : 18 tahun | Tipe:  <class 'int'>
Skor Tes Awal  : 90.0 | Tipe:  <class 'float'>
ID Token Sinyal: (6767+3j) | Tipe:  <class 'complex'>

=== STATUS KELULUSAN PRAKTIKUM ===
Batas Minimum Nilai: 75.0
Apakah Dinyatakan Lulus?: True | Tipe:  <class 'bool'>


### Penjelasan Rinci Alur Logika Program Tugas

1. **Deklarasi variabel global**  
   Program terlebih dahulu membuat variabel `nama_2027`, `kelamin_2027`, `umur_2027`, `skor_2027`, `batas_minimum_2027`, `lulus_2027`, `token_2027`, dan `alamat_2027`. Variabel-variabel tersebut menunjukkan beberapa tipe data: `str`, `int`, `float`, `bool`, dan `complex`.

2. **Fungsi `main()`**  
   Fungsi utama menampilkan judul program kemudian memanggil `bagian1()`, `bagian2()`, dan `bagian3()` secara berurutan.

3. **Fungsi `bagian1()` – input data**  
   Pengguna memasukkan nama, jenis kelamin, umur, dan skor tes awal. Umur dikonversi dengan `int()`, sedangkan skor dikonversi dengan `float()`. Kata kunci `global` memungkinkan fungsi memperbarui variabel global tersebut.

4. **Fungsi `bagian2()` – pemeriksaan data dan tipe**  
   Data yang sudah dimasukkan ditampilkan bersama hasil `type()`. Dengan demikian, program menunjukkan tipe setiap data yang digunakan.

5. **Fungsi `bagian3()` – pemeriksaan kelulusan**  
   Program menampilkan batas minimum nilai yaitu `75.0`. Kemudian terdapat perbandingan `skor_2027 >= batas_minimum_2027`.

6. **Catatan penting pada kode asli**  
   Hasil perbandingan disimpan ke variabel **`lulus_2021`**, sedangkan variabel yang dicetak adalah **`lulus_2027`**. Karena `lulus_2027` sejak awal bernilai `False` dan tidak pernah diperbarui, output status kelulusan tetap `False`. Jadi, dengan skor 85.5 pun program asli menampilkan `False`.

7. **Alur keseluruhan**  
   Deklarasi variabel → `main()` dijalankan → input data → data dan tipe data ditampilkan → skor dibandingkan dengan batas minimum → karena hasil perbandingan masuk ke `lulus_2021`, bukan `lulus_2027`, nilai yang dicetak tetap `False`.

**Formula/logika yang dimaksud pada bagian kelulusan:**

`skor_2027 >= batas_minimum_2027`

Jika `skor_2027` lebih besar atau sama dengan `75.0`, ekspresi tersebut bernilai `True`. Namun pada kode asli, hasil tersebut tidak dimasukkan ke `lulus_2027`.

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum pekan ke-2, dapat disimpulkan bahwa Python memiliki berbagai tipe data yang digunakan sesuai karakteristik informasi, seperti `string`, `int`, `float`, `complex`, dan `bool`. Fungsi `input()` dapat digunakan untuk menerima data dari pengguna, sedangkan konversi tipe diperlukan ketika data tersebut akan digunakan dalam operasi numerik.

Penggunaan konstanta juga dapat membantu menyimpan nilai tetap seperti `PI` pada perhitungan luas lingkaran. Selain itu, boolean dapat digunakan untuk menghasilkan keputusan berdasarkan suatu kondisi.

Pada program tugas, berbagai konsep tersebut digabungkan melalui variabel global, fungsi, input, pemeriksaan tipe data, dan perbandingan nilai. Analisis terhadap kode juga menunjukkan pentingnya ketepatan nama variabel, karena kesalahan penamaan seperti `lulus_2021` dan `lulus_2027` dapat menyebabkan hasil program tidak sesuai dengan logika yang diharapkan.

---
## DAFTAR PUSTAKA

[1] Python Software Foundation, "The Python Tutorial – An Informal Introduction to Python," [2026]. [Online]. Tersedia: https://docs.python.org/3/tutorial/introduction.html [Diakses Oktober 2026].

[2] Python Software Foundation, "Built-in Functions – input() dan type()," [2026]. [Online]. Tersedia: https://docs.python.org/3/library/functions.html [Diakses Oktober 2026].

[3] Python Software Foundation, "typing — Support for type hints," [2026]. [Online]. Tersedia: https://docs.python.org/3/library/typing.html [Diakses Oktober 2026].